# Generated by Django 3.0.5 on 2020-05-20 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_auto_20200520_1448'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reposted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='owner_community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='owner_community', to='community.Community'),
        ),
        migrations.AddField(
            model_name='post',
            name='rt',
            field=models.ManyToManyField(blank=True, related_name='rt', to=settings.AUTH_USER_MODEL),
        ),
    ]
