# Generated by Django 3.0.6 on 2020-05-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_music_user'),
        ('post', '0002_auto_20200520_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music',
            field=models.ManyToManyField(to='music.Music'),
        ),
    ]
