# Generated by Django 3.0.5 on 2020-05-14 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='messages/images')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_readed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(to='chat.MessageImages')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=50, null=True)),
                ('is_dialog', models.BooleanField(default=False)),
                ('base_image', models.ImageField(default='avatars/users/unknown_profile.jpg', upload_to='avatars/users')),
                ('image', models.ImageField(default='avatars/users/unknown_profile.jpg', upload_to='avatars/users')),
                ('administrators', models.ManyToManyField(related_name='chat_administrators', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(blank=True, to='chat.Message')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='chat_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
