# Generated by Django 3.0.6 on 2020-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_music_user'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='music',
            field=models.ManyToManyField(to='music.Music'),
        ),
    ]
