# Generated by Django 3.0.5 on 2020-05-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200520_1448'),
        ('user_profile', '0003_profile_custom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='post.Post'),
        ),
    ]
