# Generated by Django 3.0.6 on 2020-05-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='custom_url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
