# Generated by Django 3.0 on 2020-05-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='user',
        ),
    ]
