# Generated by Django 3.0.5 on 2020-05-14 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_image', models.ImageField(default='avatars/users/unknown_profile.jpg', upload_to='avatars/users')),
                ('image', models.ImageField(default='avatars/users/unknown_profile.jpg', upload_to='avatars/users')),
                ('job', models.CharField(max_length=100, null=True)),
                ('study', models.CharField(max_length=100, null=True)),
                ('biography', models.CharField(max_length=500, null=True)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина'), (None, 'Не указано')], max_length=1, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('birth', models.DateField(null=True)),
                ('show_email', models.BooleanField(default=False)),
                ('last_act', models.DateTimeField(default=django.utils.timezone.now)),
                ('blacklist', models.ManyToManyField(related_name='blacklist', to=settings.AUTH_USER_MODEL)),
                ('chats', models.ManyToManyField(to='chat.Chat')),
                ('communities', models.ManyToManyField(to='community.Community')),
                ('friends', models.ManyToManyField(related_name='friendlist', to=settings.AUTH_USER_MODEL)),
                ('liked_posts', models.ManyToManyField(related_name='liked_posts', to='post.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
