# Generated by Django 3.0.5 on 2020-04-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_dialog',
            field=models.BooleanField(default=False),
        ),
    ]
