# Generated by Django 3.0.4 on 2020-03-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='testfiled',
            field=models.TextField(null=True),
        ),
    ]
