# Generated by Django 3.0.5 on 2020-04-25 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta_social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimages',
            name='from_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
