# Generated by Django 3.0.5 on 2020-05-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimages',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/images/'),
        ),
    ]
