# Generated by Django 3.0.4 on 2020-04-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_social_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cropping',
        ),
        migrations.AddField(
            model_name='profile',
            name='base_image',
            field=models.ImageField(blank=True, default='avatars/users/0.png', upload_to='avatars/users'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatars/users/0.png', upload_to='avatars/users'),
        ),
    ]
