# Generated by Django 3.0.5 on 2020-04-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_social_app', '0002_chat_is_dialog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='base_image',
            field=models.ImageField(default='avatars/users/0.png', upload_to='avatars/users'),
        ),
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(default='avatars/users/0.png', upload_to='avatars/users'),
        ),
    ]
