# Generated by Django 3.0.4 on 2020-04-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_social_app', '0002_auto_20200413_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='base_image',
            field=models.ImageField(default='avatars/users/0.png', upload_to='avatars/users'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatars/users/0.png', upload_to='avatars/users'),
        ),
    ]
