# Generated by Django 3.0.4 on 2020-03-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_social_app', '0002_post_testfiled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='testfiled',
        ),
    ]
