# Generated by Django 3.0.5 on 2020-04-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_social_app', '0003_community_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_logout',
        ),
    ]
