# Generated by Django 3.0.4 on 2020-04-15 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta_social_app', '0004_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарий'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыка'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(default='Автор', max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(default='Название', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Создатель', to=settings.AUTH_USER_MODEL),
        ),
    ]
