# Generated by Django 3.0.5 on 2020-04-25 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta_social_app', '0004_auto_20200422_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='first_user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='second_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='administrators',
            field=models.ManyToManyField(related_name='chat_administrators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='base_image',
            field=models.ImageField(default='avatars/users/0.png', upload_to='avatars/users'),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(default='avatars/users/0.png', upload_to='avatars/users'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_dialog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chat_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
