# Generated by Django 3.0.5 on 2020-04-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_social_app', '0004_auto_20200424_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='administrators',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='owner',
        ),
    ]
