# Generated by Django 3.0.4 on 2020-04-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta_social_app', '0005_auto_20200415_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='community',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='user',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='community',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='community',
            name='avatar',
        ),
        migrations.AddField(
            model_name='community',
            name='base_image',
            field=models.ImageField(default='avatars/users/0.png', upload_to='avatars/communities'),
        ),
        migrations.AddField(
            model_name='community',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(default='avatars/users/0.png', upload_to='avatars/communities'),
        ),
        migrations.AddField(
            model_name='community',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meta_social_app.Community'),
        ),
        migrations.AddField(
            model_name='profile',
            name='communities',
            field=models.ManyToManyField(to='meta_social_app.Community'),
        ),
        migrations.AlterField(
            model_name='community',
            name='info',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Communities',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
