# Generated by Django 3.0.5 on 2020-04-24 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta_social_app', '0006_auto_20200424_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='administrators',
            field=models.ManyToManyField(related_name='chat_administrators', to=settings.AUTH_USER_MODEL),
        ),
    ]
